config/routes.rb
Storyline::Application.routes.draw do
  #root
  root 'app#index'

  #game
  get '/game/nieuw'                                         => 'games#new', as: :new_game
  post '/game/create'                                        => 'games#create', as: :create_game
  get '/game/:id/verhaal-tot-nu-toe'                        => 'games#story', as: :game_story

  get '/game/:id'                                           => 'games#index', as: :game
  get '/game/:id/stap/een/'                                 => 'games#stepone', as: :game_step_one
  get '/game/:id/stap/twee/:writer'                         => 'games#steptwo', as: :game_step_two_writer
  get '/game/:id/stap/twee/'                                => 'games#steptwo', as: :game_step_two
  get '/game/:id/stap/drie/'                                => 'games#stepthree', as: :game_step_three

  #round
  patch '/game/:id/een/addtext'                             => 'rounds#add_text',   as: :game_step_one_add_text

  #submittedpicture
  get '/pictures/:string'                                   => 'submittedpictures#select'
  get '/picture/show/:id'                                  => 'submittedpictures#show', as: :show_picture
  get '/pictures/:string/:writer'                           => 'submittedpictures#select', as: :find_picture

  get '/game/:id/twee/addphoto/:flickr_id/:user_id/:writer' => 'submittedpictures#select_picture',  as: :game_step_two_add_photo
  get '/game/drie/stemmen/:id'                              => 'submittedpictures#vote_picture',    as: :game_step_two_three_vote_photo

  #user
  get '/gebruiker/zoeken/'                                  => 'users#index', as: :search_user_hard
  get '/gebruiker/zoeken/:string'                           => 'users#search', as: :search_user
  get '/gebruiker/berichten/'                               => 'users#messages', as: :user_messages
  get '/gebruiker/berichten/:id'                            => 'users#read_message', as: :read_message
  get '/gebruiker/berichten/:id/:status'                    => 'users#status_message', as: :status_message
  get '/aanmelden'                                          => 'users#new', as: :sign_up
  get '/vriend/toevoegen/:id'                               => 'users#addfriend', as: :add_friend
  resources :users

  #session
  get '/inloggen'                                           => 'sessions#new', as: :sign_in
  get '/uitloggen'                                          => 'sessions#destroy', as: :sign_out
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :participant
  has_many :games, through: :participant
  has_many :friendships
  has_many :submittedpictures
  has_many :messages

  has_many :friends, through: :friendships #, source: :friend

  before_save { self.email = email.downcase }
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ # look at me rocking awesome regular expression logic! ...no seriously I hate that stuff

  def known_players
    players = Array.new()
    self.games.each do |game|
      game.participants.each do |friend|
        if players.exclude?(friend.user)
          players.push(friend.user)
        end
      end
    end

    players
  end

  def unread_messages
    Message.where(:user_id => self.id, :read => false).order("created_at ASC")
  end

  def is_friend?(user)
    if user != self
      return !user.friends.include?(self) # that looks odd for some reason ...is that just me?
    end

    false
  end

  #Add a friend synchronized.
  def add_friend(user)
    #Check if user is really a user. Also, friend yet?
    if user.instance_of?(User)
      user.friends << self
      user.save

      self.friends << user
      self.save
    else
      flash[:error] = 'Vriend kon niet worden toegevoegd.'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < AppController
  def new
    @user = User.new
  end

  def show
    #must_be_signed_in
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "U bent succesvol aangemeld, u kunt nu inloggen!"
      redirect_to sign_in_path
    else
      flash[:error] = "Er is een fout opgetreden, probeer opnieuw."
      flash[:error] = @user.errors.full_messages.first if @user.errors.any?
      render 'new'
    end
  end

  def messages
    @messages = current_user.messages
  end

  def read_message
    @message = Message.find(params[:id])

    if !@message.friend_id.nil? && @message.friend_id > 0
      @friend = User.find(@message.friend_id)
    end

    if !@message.game_id.nil? && @message.game_id > 0
      @game = Game.find(@message.game_id)
    end

    @message.read = true
    @message.save
  end

  def status_message
    @message = Message.find(params[:id])

    redirect = user_messages_path

    flash[:succes] = "Bericht is succesvol verwijderd!"

    if !@message.friend_id.nil? && @message.friend_id > 0
        if params[:status] == 1.to_s
        friend = User.find(@message.friend_id)
        current_user.add_friend(friend)
        flash[:success] = "Vriend is succesvol toegevoegd!"
      else
        flash[:error] = "Vriendschapverzoek is succesvol geweigerd!"
      end
    end

    if !@message.game_id.nil? && @message.game_id > 0
      if params[:status] == 1.to_s
        Participant.create!(:user_id => current_user.id, :game_id => @message.game_id)
        flash[:success] = "Storyline is succesvol toegevoegd!"
      else
        flash[:error] = "Verzoek tot het spelen van Storyline is succesvol geweigerd!"
      end
    end

    if !@message.round_id.nil? && @message.round_id > 0
      if params[:status] == 1.to_s
        round = Round.find(@message.round_id)
        redirect = round.game
      else
        flash[:error] = "Iets is er mis gegaan"
      end
    end

    @message.destroy
    redirect_to redirect
  end

  def addfriend
    Message.create(:user_id => params[:id], :title => 'Vriendschapsverzoek', :text => 'Wil je vrienden zijn?', :friend_id => current_user.id, :read => false)
    flash[:success] = "Vriendschapsverzoek is succesvol verzonden!"
    redirect_to :back
  end

  #TO model
  def search
    string = "%" + params[:string] + "%"

    userArray = Array.new

    #make sure there are no friends and know friends in this list.
    User.where("name like ? or email like ?", string, string).each do |user|
      if current_user.friends.exclude?(user) && current_user.known_players.exclude?(user)
        userArray.push(user)
      end
    end

    render json: userArray
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/messages.html.erb
<% provide(:title, "Berichten") %>
<h1>Berichten</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Gelezen?</th>
    <th>Titel</th>
    <th>Verzonden</th>
    <th>Lezen</th>
  </tr>
  </thead>

  <tbody>
  <% @messages.each do |bericht| %>
      <tr>
        <% if bericht.read %>
            <td>Al gelezen</td>
        <% else %>
            <td>Nog niet gelezen</td>
        <% end %>

        <td><%= link_to bericht.title, read_message_path(bericht) %></td>
        <td><%= link_to bericht.created_at, read_message_path(bericht) %></td>
        <td><%= link_to "Lezen", read_message_path(bericht) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, "Registreren") %>
<h1>Registreren</h1>

<div class="row">
  <div class="span6">
    <%= form_for(@user) do |f| %>
        <%= f.label "naam" %>
        <%= f.text_field :name, placeholder: "naam" %>

        <%= f.label "E-mail" %>
        <%= f.text_field :email, placeholder: "e-mailadres" %>

        <%= f.label "Password" %>
        <%= f.password_field :password, placeholder: "Password invoeren" %>

        <%= f.label "Wachtwoord bevestigen" %>
        <%= f.password_field :password_confirmation, placeholder: "Voer nogmaals password in" %>

        <%= f.submit "Klaar!", class: "btn" %>
    <% end %>

    <p>Heeft u al een account? <%= link_to "Klik hier om naar de inlogpagina te gaan, sign_in_path, class: 'btn btn-inverse' %></p>-->
  </div>
</div>

app/views/users/read_message.html.erb
<% provide(:title, @message.title) %>
<h1><%= @message.title %></h1>


    <span><%= @message.text %></span>

<%= link_to 'Bericht verwijderen', status_message_path(@message.id, 0), class: 'btn' %>

<% if !@message.friend_id.nil? && @message.friend_id > 0 # this really isn't very elegant, can this be improved? %> 
    <div>
      <h2>Wil je vrienden worden?</h2>
      
        <span><%= @friend.name %> heeft je toevegoegd als vriend. Wil je vrienden zijn? Accepteer dan de uitnodiging:</span>
        <%= link_to 'Accepteren', status_message_path(@message.id, 1), class: 'btn' %>
        <%= link_to 'Weigeren', status_message_path(@message.id, 0), class: 'btn' %>
      
    </div>
<% end %>

<% if !@message.game_id.nil? && @message.game_id > 0 # I still don't like the look of that, but it works %>
    <div>
      <h2><b>Je bent uitgedaagd tot een spelletje Storyline!</b></h2>
      
        <span>Je bent uitgedaagd voor een spelletje Storyline. Wil jij laten zien wat je kunt?</span>
        <%= link_to ' Ja', status_message_path(@message.id, 1), class: 'btn' %>
        <%= link_to ' Nee dank je', status_message_path(@message.id, 0), class: 'btn' %>
      
    </div>
<% end %>

<% if !@message.round_id.nil? && @message.round_id > 0 %>
    <div>
      <h2>Voortgang van storyline inzien</h2>
      
        <span>Kijk snel wat de voortgang is in de storyline:</span>
        <%= link_to 'Tonen', status_message_path(@message.id, 1), class: 'btn' %>
        <%= link_to 'Niet nu', status_message_path(@message.id, 0), class: 'btn'%>
      
    </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, "Gebruikers info") %>
<h1>Gebruikers info</h1>

<h2>Mijn details</h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Naam</th>
    <th>E-mailadres</th>
    <th>Datum van aanmelding</th>
  </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @user.name %></td>
        <td><%= @user.email %></td>
        <td><%= @user.created_at %></td>
      </tr>
  </tbody>
</table>

<h2>Storylines</h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Storyline nummer</th>
    <th>Aantal deelnemers</th>
    <th>Begonnen op</th>
    <th>aantal rondes</th>
    <th>Verhaalpanelen tot nu toe</th>
    <th>Status</th>
  </tr>
  </thead>

  <tbody>
  <% @user.games.each do |spel| %>
      <tr>
        <td><%= link_to spel.id, spel %></td>
        <td><%= link_to spel.participants.count, spel %></td>
        <td><%= link_to spel.created_at, spel %></td>
        <td><%= link_to spel.rounds.count, spel %></td>
        <td><%= link_to "Verhaalpanelen tot nu toe", game_story_path(spel) %></td>
        <td>
            <div class="progress progress-striped active">
                <div class="bar" style="width: <%=  100 / spel.get_status %>%;"></div>
            </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<h2>Vrienden</h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Naam</th>
    <th>E-mailadres</th>
    <th>Geregistreerd op</th>
  </tr>
  </thead>

  <tbody>
  <% @user.friends.each do |vriend| %>
      <tr>
        <td><%= link_to vriend.name, vriend %></td>
        <td><%= link_to vriend.email, vriend %></td>
        <td><%= link_to vriend.created_at, vriend %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<% if !current_user.nil? &&  current_user.is_friend?(@user) %>
    <%= link_to 'Vriendschapsverzoek verzenden', add_friend_path, class: 'btn' %>
<% end %>