config/routes.rb
Storyline::Application.routes.draw do
  #root
  root 'app#index'

  #game
  get '/game/nieuw'                                         => 'games#new', as: :new_game
  post '/game/create'                                        => 'games#create', as: :create_game
  get '/game/:id/verhaal-tot-nu-toe'                        => 'games#story', as: :game_story

  get '/game/:id'                                           => 'games#index', as: :game
  get '/game/:id/stap/een/'                                 => 'games#stepone', as: :game_step_one
  get '/game/:id/stap/twee/:writer'                         => 'games#steptwo', as: :game_step_two_writer
  get '/game/:id/stap/twee/'                                => 'games#steptwo', as: :game_step_two
  get '/game/:id/stap/drie/'                                => 'games#stepthree', as: :game_step_three

  #round
  patch '/game/:id/een/addtext'                             => 'rounds#add_text',   as: :game_step_one_add_text

  #submittedpicture
  get '/pictures/:string'                                   => 'submittedpictures#select'
  get '/picture/show/:id'                                  => 'submittedpictures#show', as: :show_picture
  get '/pictures/:string/:writer'                           => 'submittedpictures#select', as: :find_picture

  get '/game/:id/twee/addphoto/:flickr_id/:user_id/:writer' => 'submittedpictures#select_picture',  as: :game_step_two_add_photo
  get '/game/drie/stemmen/:id'                              => 'submittedpictures#vote_picture',    as: :game_step_two_three_vote_photo

  #user
  get '/gebruiker/zoeken/'                                  => 'users#index', as: :search_user_hard
  get '/gebruiker/zoeken/:string'                           => 'users#search', as: :search_user
  get '/gebruiker/berichten/'                               => 'users#messages', as: :user_messages
  get '/gebruiker/berichten/:id'                            => 'users#read_message', as: :read_message
  get '/gebruiker/berichten/:id/:status'                    => 'users#status_message', as: :status_message
  get '/aanmelden'                                          => 'users#new', as: :sign_up
  get '/vriend/toevoegen/:id'                               => 'users#addfriend', as: :add_friend
  resources :users

  #session
  get '/inloggen'                                           => 'sessions#new', as: :sign_in
  get '/uitloggen'                                          => 'sessions#destroy', as: :sign_out
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :participants
  has_many :users, through: :participants
  has_many :rounds

  def participant(user)
    Participant.where(:game_id => self.id, :user_id => user.id)[0]
  end

  def get_status
    last_round = self.rounds.last

    unless last_round.nil?
      if last_round.submittedpictures.count >= self.participants.count
        return 1
      end

      if last_round.storyFragment != ''
        return 2
      end

      if last_round.storyFragment == ''
        return 3 # I freely admit that I don't really understand what I was doing when I wrote this now I look back at it ...but it doesn't break
      end
    end

    100
  end
end

app/controllers/games_controller.rb
class GamesController < AppController
  def index
    @game = Game.find(params[:id])

    if @game.rounds.count == 0
      @round = Round.create(game: @game)
    end
  end

  def new
  end

  def create

    if(params.has_key?(:users) and !params[:users].nil?)
      game = Game.create()
      params[:users].each do |user_id|
        Message.create(:user_id => user_id, :title => params[:title], :text => params[:text], :game_id => game.id, :read => false)
      end
      flash[:succes] = "Uitnodigingen succesvol aangemaakt"
      redirect_to game
    else
      flash[:error] = "Selecteer ten minste een gebruiker om uitnodiging te versturen"
      render 'new'
    end

  end

  def story
    @game = Game.find(params[:id])
  end

  def stepone
    must_be_signed_in
    @game = Game.find(params[:id])

    @round = @game.rounds.last
  end

  def steptwo
    must_be_signed_in
    @game = Game.find(params[:id])

    if params[:writer].nil?
      @writer = 0
    else
      @writer = params[:writer]
    end
  end

  def stepthree
    must_be_signed_in
    @game = Game.find(params[:id])

    if @game.rounds.last.vote_count.to_s >= @game.rounds.last.submittedpictures.count.to_s && @game.rounds.last.final_picture.nil?
      count_round(@game, @game.rounds.last)
    end

    if @game.get_status == 1
      flickr_auth

      pictures = @game.rounds.last.submittedpictures

      @pictures = Array.new()

      pictures.each do|picture|
        Rails.logger.debug(picture)
        info = flickr.photos.getInfo(:photo_id => picture.flickr_id)
        @pictures.push(:photo => FlickRaw.url_b(info), :flickr_id => picture.flickr_id, :picture_id => picture.id)
      end
    end
  end

  private

  def count_round(game, round)
    round.submittedpictures.each do |picture|
      participant = game.participant(picture.user)

      if participant.score.nil?
        participant.score = 0
      end

      if picture.nrVotes.nil?
        picture.nrVotes = 0
      end

      multiplieValue = 5
      if(picture.user.id == round.storyteller.id)
        multiplieValue = 8
      end

      participant.score = participant.score + (picture.nrVotes * multiplieValue)
      participant.save
    end

    submittecpicture = round.max_votes_picture
    submittecpicture.isFinalPicture = true
    submittecpicture.save

    notify_players(@game)

    Round.create(:game => @game)

    redirect_to @game
  end

  def notify_players(game)
    game.participants.each do |participant|
      Message.create(:user_id => participant.user.id, :title => "Ronde ##{game.rounds.count} is voorbij", :text => "De ronde ##{game.rounds.count} is afgelopen, bekijk je scores!", :round_id => game.rounds.last.id, :read => false)
    end

    flash[:succes] = "Het spel is afgelopen. Kijk in het speloverzicht wat de score is geworden!"
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1>Storyline #<%= @game.id %> - Paneel #<%= @game.rounds.count %></h1>

<div class="alert alert-info">
  Start een nieuw spel of voeg leden toe.
  
  <%= link_to ' Start nieuwe storyline', new_game_path, class: 'btn' %>
  <%= link_to ' Vrienden toevoegen', current_user, class: 'btn' %>
</div>


  <h2>Nog <%= @game.get_status %> stappen te gaan voor de volgende ronde begint!</h2>
  <div class="progress progress-striped active">
    <div class="bar" style="width: <%=  100 / @game.get_status %>%;"></div>
  </div>


<% if @game.rounds.count > 0 && @game.rounds.last.storyFragment.to_s == '' %>
    <%= link_to ' Stap 1', game_step_one_path(@game.id), class: 'btn' %>
<% end %>

<% if @game.rounds.count > 0 && @game.rounds.last.storyFragment != '' %>
    <%= link_to ' Stap 2', game_step_two_path(@game.id), class: 'btn' %>
<% end %>

<% if !current_user.nil? && !@game.rounds.last.nil? && @game.rounds.last.submittedpictures.where("user_id", current_user.id).count > 1 && @game.rounds.last.submittedpictures.count >= @game.participants.count %>
    <%= link_to ' Stap 3', game_step_three_path(@game.id), class: 'btn' %>
<% end %>

<h1>Deelnemers</h1>


  <h2>Spelers</h2>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Naam</th>
      <th>Score</th>
      <th>Link</th>
      <th>Volgers</th>
    </tr>
    </thead>

    <tbody>
    <% @game.participants.each do |deelnemer| %>
        <%
           if deelnemer.score.nil?
             deelnemer.score = 0 # beetje hacky dit, maar het werkt
           end
        %>
        <tr>
          <td><%= link_to deelnemer.user.name, deelnemer.user %></td>
          <td><%= link_to deelnemer.score, deelnemer.user %></td>
          <td><%= link_to "Tonen", deelnemer.user %></td>
          <td>
            <% if !current_user.nil? && current_user.is_friend?(deelnemer.user) %>
                <%= link_to  ' Toevoegen als vriend', add_friend_path(deelnemer.user), class: 'btn'%> 
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>


<h1>Tot nu toe gespeelde rondes</h1>
<% @game.rounds.each do |ronde| %>
    <% if ronde.submittedpictures.count != 0 %>
    
      <h2>Het verhaal: <%= ronde.storyFragment %></h2>

      <table class="table table-striped">
        <thead>
        <tr>
          <th>Naam</th>
          <th>Aantal stemmen</th>
          <th>Link</th>
        </tr>
        </thead>

        <tbody>
            <% ronde.submittedpictures.each do |foto| %>
                <%
                   if foto.nrVotes.nil?
                     foto.nrVotes = 0 # daar issie weer
                   end
                %>
                <tr>
                  <% if foto.user.id != ronde.storyteller.id %>
                       <td><%= link_to foto.user.name, show_picture_path(foto.flickr_id) %></td>
                  <% else %>
                      <td><%= link_to foto.user.name + " (Storyteller)", show_picture_path(foto.flickr_id) %></td>
                  <% end %>
                  <td><%= link_to foto.nrVotes, show_picture_path(foto.flickr_id) %></td>
                  <td><%= link_to "Foto tonen", show_picture_path(foto.flickr_id), :target => "_blanc" %></td>
                </tr>
            <% end %>
        </tbody>
      </table>
    
    <% end %>
<% end %>

app/views/games/new.html.erb
<% provide(:title, "Een nieuw spel beginnen!") %>
<h1>Een nieuw spel beginnen</h1>

<%= form_tag(create_game_path()) do -%>
    <h2>Vul hier een awesome titel en uitnodigingstekst in</h2>
    
        <input  type="text" placeholder="Awesome titel" name="title">
        <textarea  placeholder="Awesome tekst" name="text"></textarea>
    </div>

    <h2>Voeg nieuwe deelnemers toe </h2>
    
      <input type="text"  id="search" placeholder="Zoeken op naam of e-mailadres" />
      <div id="user-box">

      </div>
    


    <h2>Selecteer vrienden die je wilt uitnodigen</h2>
    
      <% current_user.friends.each do |vriend| %>
          
            <p><%= vriend.name %></p>
            Uitnodigen: <input type="checkbox" name="users[<%= vriend.id %>]" value="1">
          
      <% end %>
    </div>

    
    <h2>Begin de storyline</h2>
    
        <p>Druk op de knop hieronder om de storyline te starten. </p>
        <input type="submit" class="btn" value="Start storyline" />
    
<% end -%>

<script type="text/javascript">
    $(document).on('click', '.add-user', function(){
        var
        id = $(this).data('id'),
        name = $(this).data('name'),
        htmlString = "";

        
        htmlString += '<p>' + name + '</p>';
        htmlString += 'Uitnodigen: <input type="checkbox" name="users[' + id + ']" value="1">';
        

        $('#users-box').prepend(htmlString);
    });

    $('#search').on('keyup', function() {
        function ToonGegevens(data) {
            var htmlString = "";

            for (var i = 0; i < data.length; i++) {
                
                htmlString += data[i].name;
                htmlString += '<div data-id="' + data[i].id + '" data-name="' + data[i].name + '">Toevoegen aan lijst</div>';
                
            }

            $('#user-box').html(htmlString);
        }

        if(this.value != ''){
            $.ajax(
            {
                type: 'GET',
                url: "/gebruiker/zoeken/" + this.value,
                async: true,
                success: function(data)
                {
                    ToonGegevens(data)
                }
            });
        }
    });
</script>

app/views/games/stepone.html.erb
<% provide(:title, "Stap 1") %>
<h1>Voeg verhaaltekst toe aan het paneel</h1>


  <h2>Nog 2 stappen voor de volgende ronde</h2>
    <div class="progress progress-striped active">
      <div class="bar" style="width: <%=  100 / @game.get_status %>%;"></div>
    </div>


<div class="row">
  <div class="span6">
    <%= form_for(@round, url: game_step_one_add_text_path(@round)) do |f| %>
        <%= f.label "Verhaaltekst" %>
        <%= f.text_area :storyFragment, placeholder: "Schrijf een passend verhaalfragment" %>

        <%= f.submit "Volgende stap", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/games/stepthree.html.erb
<% if @game.get_status == 1 %>
    <% provide(:title, "Stap 2: Stem op een plaatje") %>
    <h1>Stemmen!</h1>

    <p>Nu is het tijd een plaatje te kiezen voor het ingevulde tekstfragment. Hieronder volgt de ingevoerde tekst. Succes! </p>
    

          <%= @game.rounds.last.storyFragment %>
        
    

    
      <% @pictures.each do |foto| # MEMO: I love the each method. I really, really do! :) %>
          <%= link_to image_tag(foto[:photo], alt: "Nutteloze alt-tekst", title: "Dit vind ik de beste!", class: "img-polaroid"),  game_step_two_three_vote_photo_path(foto[:picture_id]) %>
      <% end %>
    </div>
<% else %>
    <% provide(:title, "Stap drie") %>
    <h1><b>Tik ...tak ...tik ...tak ...</b></h1>

    
      <p>Saai hë, dat wachten? Ga anders wat koffie zetten. Eerst moeten alle spelers gestemd hebben </p>
      <div class="progress progress-striped active">
        <div class="bar" style="width: <%=  100 / (@game.get_status - (@game.rounds.last.submittedpictures.count.to_f / @game.participants.count.to_f)) %>%;"></div>
      </div>
      <p>Er zijn al <%= @game.rounds.last.submittedpictures.count %> foto's ingeleverd van de <%= @game.participants.count %>.</p>
    </div>
<% end %>

app/views/games/steptwo.html.erb
<% provide(:title, "Stap 2") %>
<h1>Nu een willekeurige foto uitkiezen</h1>


  <p>Dit is stap 2, waar een foto moet worden gekozen voor het ingevoerde stukje tekst </p>
  <div class="progress progress-striped active">
    <div class="bar" style="width: <%=  100 / @game.get_status %>%;"></div>
  </div>
</div>


  <p>Gebruik het invoerveld om zogenaamde 'tags' (sleutelwoorden) voor de foto in te toetsen. Gebruik tags die te maken hebben met de tekst die in stap 1 is ingevoerd. Of ...niet. Wees creatief! </p>
    <div>
      <input type="text" id="search" placeholder="Voer hier zoekwoorden in" />
    </div>
    <div id="img-box">

    </div>
</div>

<script type="text/javascript">
    var game_id = <%= @game.rounds.last.id %>,
      user_id = <%= current_user.id %>,
      writer = <%= @writer  %>;

    $('#search').on('change', function() {
        function ToonAfbeeldingen(data) {
            var htmlString = "<h2>Kies een leuke bijpassende foto bij de ingevoerde tekst</h2><p><%= @game.rounds.last.storyFragment %></p>";

            for (var i = 0; i < data.length; i++) {
                htmlString += '<a href="/game/' + game_id + '/twee/addphoto/' + data[i].flickr_id + '/' + user_id + '/' + writer + '">';
                htmlString += '<img class="img-polaroid" title="' + data[i].flickr_id + '" src="' + data[i].photo;
                htmlString += '" alt="'; htmlString += data[i].title + '" />';
                htmlString += '</a>';
            }

            $('#img-box').html(htmlString);
        }

        $.ajax(
        {
            type: 'GET',
//            url: "http://localhost:3000/submittedpictures/select/" + this.value,
            url: "/pictures/" + this.value,
            async: true,
            success: function(data) {
			    alert("Works!");
                {
                    ToonAfbeeldingen(data);
                }
            }
        });
    });
</script>

app/views/games/story.html.erb
<% provide(:title, "Het verhaal!") %>
<h1>Het verhaal.</h1>
<% rounds = @game.rounds.reverse %>
<% rounds.each do |ronde| %>
    <% if !ronde.storyteller.nil?  %>
        
        <h2><%= ronde.storyteller.name %> schreef het volgende:</h2>
        <span><%= round.storyFragment %></span>
          <% if !ronde.final_picture.nil? %>
              <p><%= image_tag(ronde.final_picture.get_link[:photo], alt: "Foto", class: "img-polaroid") %></p>
          <% else %>
            <p>De stemmen zijn nog niet binnen, dus de laatste foto is nog niet bekend.</p>
          <% end %>
        </div>
    <% end %>
<% end %>